/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cloud_logic_custom": [
        {
            "name": "processAPI",
            "endpoint": "https://y0n7g4lryh.execute-api.eu-north-1.amazonaws.com/dev",
            "region": "eu-north-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "eu-north-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Users-dev",
            "region": "eu-north-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-north-1:4a33a796-e195-4fa6-a435-c51065c4b0a6",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_yoOq8wfUe",
    "aws_user_pools_web_client_id": "g6afgk3l0o67n26m07h2m584n",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
